// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3XvvcHaFLyNR__O4XrWewqXJtBpMKecE',
    appId: '1:384835216940:web:594d293732c70785b1d389',
    messagingSenderId: '384835216940',
    projectId: 'novel-architect-a5b19',
    authDomain: 'novel-architect-a5b19.firebaseapp.com',
    storageBucket: 'novel-architect-a5b19.firebasestorage.app',
    measurementId: 'G-6FVC7JQW8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeWv73xrCDksVVW2ONdfG3w2PsV_EeHxE',
    appId: '1:384835216940:android:3f5723626fff8021b1d389',
    messagingSenderId: '384835216940',
    projectId: 'novel-architect-a5b19',
    storageBucket: 'novel-architect-a5b19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXdMP4faAJjw7VK-33Wt6rrUivhuMoEL0',
    appId: '1:384835216940:ios:0d7a0a9a51b67f4db1d389',
    messagingSenderId: '384835216940',
    projectId: 'novel-architect-a5b19',
    storageBucket: 'novel-architect-a5b19.firebasestorage.app',
    iosBundleId: 'com.example.novelarchitect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXdMP4faAJjw7VK-33Wt6rrUivhuMoEL0',
    appId: '1:384835216940:ios:0d7a0a9a51b67f4db1d389',
    messagingSenderId: '384835216940',
    projectId: 'novel-architect-a5b19',
    storageBucket: 'novel-architect-a5b19.firebasestorage.app',
    iosBundleId: 'com.example.novelarchitect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3XvvcHaFLyNR__O4XrWewqXJtBpMKecE',
    appId: '1:384835216940:web:46cbcf7e17f27865b1d389',
    messagingSenderId: '384835216940',
    projectId: 'novel-architect-a5b19',
    authDomain: 'novel-architect-a5b19.firebaseapp.com',
    storageBucket: 'novel-architect-a5b19.firebasestorage.app',
    measurementId: 'G-KJPG8ZKW8E',
  );
}
